WebTuyenSinhAdmin/Controllers/ManagerSchoolController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebTuyenSinh.Data.Entityes;
using WebTuyenSinh_Application.Interface;
using WebTuyenSinh_Application.Modell;
using WebTuyenSinh_Application.ViewApi;
using WebTuyenSinhAdmin.Contan;

namespace WebTuyenSinhAdmin.Controllers
{
    public class ManagerSchoolController : Controller
    {
        private readonly IValidateTokenService _IValidateTokenService;
        private readonly ISchoolService service;
        private readonly IExcellService _IExcellService;
        public ManagerSchoolController(ISchoolService service, IExcellService IExcellService,
            IValidateTokenService IValidateTokenService)
        {
            this.service = service;
            _IExcellService = IExcellService;
            _IValidateTokenService = IValidateTokenService;
        }

        public async Task<IActionResult> Index(string ShoolName, int? page=0)
        {
            string cookie = Request.Cookies[UserContant.UseToken];
    
            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
            
            List<School> schools =(List<School>) await  service.GetAll();
            if (ShoolName != null && ShoolName.Length > 0) { schools = schools.Where(x => x.NameShool.Contains(ShoolName)).ToList(); } else
            {
                ShoolName = "";
            }
                int limit = 10;
            int start;
            if (page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            }
            start = (int)(page - 1) * limit;
            ViewBag.pageCurrent = page;
            ViewBag.Search = ShoolName;
            int totalProduct = schools.Count;
            float numberpage = totalProduct / limit;
            ViewBag.numberPage = (int) Math.Ceiling(numberpage);
           
            var check  = await  _IValidateTokenService.ValidateToken(cookie, new List<long>() { PermisstionConTant.QL_TH,PermisstionConTant.QL_TS});
            if (check)
            {
                return View(schools.Skip(start).Take(limit).ToList()); ;
            }
            return View("IndexUse", schools.Skip(start).Take(limit).ToList());
        }

        public IActionResult ViewExcel()
        {
            try {
                string cookie = Request.Cookies[UserContant.UseToken];

                if (cookie == null || cookie.Length == 0)
                {
                    return RedirectToAction("Index", "Account");
                }
                string shool = HttpContext.Session.GetString("School");
                var api = JsonConvert.DeserializeObject<List<School>>(shool);
                if (api.Count > 0)
                {
                    api.RemoveAt(0);
                }

                return View(api);

            } catch { return RedirectToAction("Index"); }
           
        }
        public async Task<IActionResult> Save()
        {
            try {
                string cookie = Request.Cookies[UserContant.UseToken];
                if (cookie == null || cookie.Length == 0)
                {
                    return RedirectToAction("Index", "Account");
                }
                string shool = HttpContext.Session.GetString("School");
                var api = JsonConvert.DeserializeObject<List<School>>(shool);
                if (api.Count > 0)
                {
                    api.RemoveAt(0);
                  await service.ListCreate(api);             
                }
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");

        }


          public async Task<IActionResult> DeleteShool(long id)
        {
        
            return Ok(await service.Delete(id));
        }

        public IActionResult Import(string ViewSchool)
        {
            string cookie = Request.Cookies[UserContant.UseToken];
            HttpContext.Session.SetString("School", ViewSchool);
            return Ok("ok");

        }

        public async Task<IActionResult> Update(long id)
        {
            string cookie = Request.Cookies[UserContant.UseToken];

            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
            var check = await _IValidateTokenService.ValidateToken(cookie, new List<long>() { PermisstionConTant.QL_TH, PermisstionConTant.QL_TS });
            if (check)
            {
                ApiResult apiResult =  await service.GetByID(id);
                School School= (School) apiResult.Data;
                List<School> schools = new List<School>();
                schools.Add(School);
                return View(schools);
            }
            return View("UseNotFound");
        }

        public IActionResult Create(string ViewSchool)
        {
            string cookie = Request.Cookies[UserContant.UseToken];
            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
        
            return View();

        }
    }
}

WebTuyenSinhAdmin/Views/ManagerSchool/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="col-md-12">
    <div class="card">
        <div class="m-3">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Danh Sách Các Trường</h4>
                <div class="ml-auto">

                    <button id="btnNhan" onclick="$('#txtFile').trigger( 'click' )" class="btn btn-primary btn-round ml-auto" data-target="#addRowModal">
                        <i class="ti-export"></i>
                        Tải File
                    </button>
                    <a class="btn btn-primary btn-round ml-auto" href="~/dowload/BieuMauTruong.xls" download>
                        <i class="ti-download"></i>
                        Dowload File
                    </a>
                    <input id="txtFile" onchange="readURL(this);" hidden type="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
                </div>
            </div>
        </div>
        <form id="formshool">
            <div class="card-body">

                <div class="table-responsive">

                    <table id="" class=" text-center display expandable-table" style="width:2500px">
                        <thead>
                            <tr>
                                <th>Mã Tỉnh/TP</th>
                                <th>Tên Tỉnh/TP </th>
                                <th>Mã Quận/Huyện</th>
                                <th>Tên Quận/Huyện</th>
                                <th>Mã Trường</th>
                                <th>Tên Trường</th>
                                <th>Địa Chỉ</th>
                                <th>Khu Vực</th>
                                <th>Trường DTNT</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="tbbody">
                        </tbody>
                    </table>



                </div>
            </div>

            <div class="col-12 text-center">
                <button type="submit" asp-controller="ManagerSchool" asp-action="Create" class="col-1 btn btn-primary">
                    Lưu
                </button>
            </div>
        </form>
      

    </div>
</div>

@section Scripts{

    <script>
    let arr = []
    var data = null;
    let cout = 10000;
    let majorsnew = [];
    let blocknew = [];
    function LoadData(i) {
        let tr =`    <tr>
                            <td style="width:150px">
                                <input class="idConscious form-control" required  />
                            </td>
                            <td style="width:400px">
                                <input required class="NameConscious form-control" />
                            </td>
                            <td style="width:150px">
                                <input required class=" idDistrict form-control" />
                            </td>
                            <td style="width:400px">
                                <input required class=" NameDistrict form-control" />
                            </td>
                            <td style="width:150px">
                                <input required class=" idSchool  form-control" />
                            </td>
                            <td style="width:400px">
                                <input required class=" NameSchool form-control" />
                            </td>
                            <td style="width:400px">
                                <input required class="adress form-control" />
                            </td>
                            <td style="width:150px">
                                <select required  class=" Area form-control">
                                     <option value="KV1"> KV1</option>
                                <option value="KV2"> KV2</option>
                                <option value="KV3"> KV3</option>
                                <option value="KV4"> 2NT</option>

                                </select>
                            </td>
                            <td>
                                <input required class=" SchoolDTNT form-control" />
                            </td>
                       <td>
                                                    <div class="form-button-action">

                                                        <button hef="/DeleteShool"   name="Delete" data-toggle="tooltip" title="" class="btn  btn-icon-text text-danger" data-original-title="Remove">
                                                            <i class="ti-close"></i>
                                                        </button>
                                                    </div>
                                                </td>

                        </tr>`

        $("#tbbody").append(tr)

        tr = ` <tr>
                            <td>
                                <button type="button" id="${i}" name="add" data-toggle="tooltip" title="" class="btn  btn-icon-text text-primary  " data-original-title="Edit Task">
                                    <i class="ti-plus"></i>
                                </button>
                            </td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>`

        $("#tbbody").append(tr)
    }
        $(document).ready(function () {
            $("#tbbody").empty();
        LoadData(cout);
        $(document).on('click', "button[name = 'Delete']", function () {
            $(this).closest('tr').remove();
            if ($('.idConscious').length == 0) {
                $("#tbbody").empty()
                cout = 1000;
                LoadData(cout);
                cout++;
            }

        })

        $("#btnAdd").click(function () {
        

        });
        $('#formshool').on('submit', function (e) {
            e.preventDefault(); // Now nothing will happen
            let check = true;
            arr = [];
            arr.push({
                idConscious: "",
                NameConscious: "",
                idDistrict: "",
                NameDistrict: "",
                NameShool: "",
                idShool: "",
                Adrees: "",
                Area: "",
            })
            for (var i = 0; i < $('.idConscious').length; i++) {
                arr.push({
                    idConscious: $($('.idConscious')[i]).val(),
                    NameConscious: $($('.NameConscious ')[i]).val(),
                    idDistrict: $($('.idDistrict')[i]).val(),
                    NameDistrict: $($('.NameDistrict')[i]).val(),
                    idShool: $($('.idSchool')[i]).val(),
                    NameShool: $($('.NameSchool ')[i]).val(),
                    Adrees: ($($('.adress')[i]).val() ? $($('.idConscious')[i]).val() : ""),
                    Area: $($('.Area')[i]).val(),
                })
                if (arr.length > 0) {
                    $.ajax({
                        url: "/ManagerSchool/Import",
                        type: 'POST',
                        data: { ViewSchool: JSON.stringify(arr) },
                        success: function (data) {
                            //...
                            window.location = "/ManagerSchool/ViewExcel"

                        }
                    });
                }

            }

           

        });

        $(document).on('click', "button[name = 'add']", function () {

            $(this).closest('tr').remove();

            $(this).hide();
            LoadData(cout)
            cout++;
         //   }

        });


    })

    </script>
    <script>
        $("#tbbody").hide();
        function readURL(event) {

            var file = event.files[0];
            var reader = new FileReader();
            var excelData = [];
            var maphong1 = event.title;

            reader.onload = function (event) {
                var data = event.target.result;
                var workbook = XLSX.read(data, {
                    type: 'binary'
                }); $("#tbbody").empty();
                workbook.SheetNames.forEach(function (sheetName) {
                    // Here is your object
                    var XL_row_object = XLSX.utils.sheet_to_row_object_array(workbook.Sheets[sheetName]);
                    var arr = [];
                    console.log(XL_row_object);
       
                    for (var i = 1; i < XL_row_object.length; i++) {
                        arr.push({
                            idConscious: XL_row_object[i]["__EMPTY"],
                            NameConscious: XL_row_object[i]["__EMPTY_1"],
                            idDistrict: XL_row_object[i]["__EMPTY_2"],
                            NameDistrict: XL_row_object[i]["__EMPTY_3"],
                            NameShool: XL_row_object[i]["__EMPTY_5"],
                            idShool: XL_row_object[i]["__EMPTY_4"],
                            Adrees: (XL_row_object[i]["__EMPTY_6"] ? XL_row_object[i]["__EMPTY_6"] : ""),
                            Area: XL_row_object[i]["__EMPTY_7"],
                        })


                    }
                    if (arr.length > 2) {
                        $.ajax({
                            url: "/ManagerSchool/Import",
                            type: 'POST',
                            data: { ViewSchool: JSON.stringify(arr) },
                            success: function (data) {
                                //...
                                window.location = "/ManagerSchool/ViewExcel"

                            }
                        });
                    }
                })
            }; reader.onerror = function (ex) {
                console.log(ex);
            };
            reader.readAsBinaryString(file);

        }

        $(document).ready(function () {
            $("#tbbody").show();
        })


                            // Add Row



    </script>
}

WebTuyenSinhAdmin/Views/ManagerSchool/IndexUse.cshtml
@{

}
@model IEnumerable<School>
@using WebTuyenSinh.Data.Entityes;
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New message</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Recipient:</label>
                        <input type="text" class="form-control" id="recipient-name">
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">Message:</label>
                        <textarea class="form-control" id="message-text"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Send message</button>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12">
    <div class="card">
        <div class="m-3">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Danh Sách Các Trường</h4>

            </div>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <form method="get" asp-controller="ManagerSchool" asp-action="Index">
                    <div class="d-flex align-items-center">
                        <div class="ml-auto">
                            <input type="text" value="@ViewBag.Search" name="ShoolName" class="form-control" placeholder="Tim kiếm" aria-label="Recipient's username" aria-describedby="button-addon2">
                        </div>
                    </div>

                    <br />
                    <br />
                    <table id="" class="table-striped  table-hover display expandable-table" style="width:100%">
                        <thead>
                            <tr>
                                <th>Mã Trường</th>
                                <th>Tên Trường</th>
                                <th>Quận Huyện</th>
                                <th>Tỉnh</th>
                                <th>Khu Vực</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody id="tbbody">
                            @foreach (var item in Model)
                            {

                                @try
                                {
                                    <tr>
                                        <td>@item.idShool</td>
                                        <td>@item.NameShool</td>
                                        <td>@item.NameDistrict</td>
                                        <td>@item.NameConscious</td>
                                        <td>@item.Area</td>
                        
                                    </tr>
                                }
                                catch { }

                            }
                        </tbody>
                    </table>
                    <br />
                    <div class="d-flex align-items-center">
                        <div class="ml-auto">
                            <ul class="pagination">
                                @{
                                    int numberPage = ViewBag.numberPage;
                                    int pageCurrent = ViewBag.pageCurrent;
                                    int offset = 2;//number display page


                                    //config FirstLink
                                    if (pageCurrent > 1)
                                    {
                                        int prevPage = pageCurrent - 1;
                                        var PrevLink = new Dictionary<string, string> { { "page", prevPage.ToString() } };
                                        <li><a asp-controller="ManagerSchool" asp-action="Index" asp-all-route-data="PrevLink">Prev Link</a></li>
                                    }

                                    int from = pageCurrent - offset;
                                    int to = pageCurrent + offset;
                                    if (from <= 0)
                                    {
                                        from = 1;
                                        to = offset * 2;
                                    }


                                    if (to > numberPage)
                                    {
                                        to = numberPage;
                                    }

                                    int i;
                                    for (i = from; i <= to; i++)
                                    {
                                        var parms = new Dictionary<string, string>
                                                                                                                                                {
                        { "page",i.ToString()},{"ShoolName",ViewBag.Search}
                            };
                                        if (pageCurrent == i)
                                        {
                                            <li class="active"><a asp-controller="ManagerSchool" asp-action="Index" asp-all-route-data="parms">@i</a></li>
                                        }
                                        else
                                        {
                                            <li><a asp-controller="ManagerSchool" asp-action="Index" asp-all-route-data="parms">@i</a></li>
                                        }

                                    }

                                    if (pageCurrent < numberPage - (to / 2))
                                    {
                                        <li><a>...</a></li>
                                        var LastLink = new Dictionary<string, string> { { "page", numberPage.ToString() } };
                                        <li><a asp-controller="ManagerSchool" asp-action="Index" asp-all-route-data="LastLink">Last Link</a></li>
                                    }

                                    if (pageCurrent < numberPage)
                                    {
                                        int nextPage = pageCurrent + 1;
                                        var NextLink = new Dictionary<string, string> { { "page", nextPage.ToString() } };
                                        <li><a asp-controller="ManagerSchool" asp-action="Index" asp-all-route-data="NextLink">Next Link</a></li>
                                    }
                                }
                            </ul>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $("#tbbody").hide();

        $(document).ready(function () {
            $("#tbbody").show();
        })

        $('#multi-filter-select').DataTable({
            "pageLength": 10,
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select class="form-control"><option value=""></option></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });

    </script>
}

WebTuyenSinhAdmin/Views/ManagerSchool/Update.cshtml
@model List<School>
@{

}
@using WebTuyenSinh.Data.Entityes;
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="m-3 border-bottom pb-3">
            <div class="d-flex align-items-center">
                <h4 class="card-title">Danh Sách Các Trường</h4>
                <div class="ml-auto">
                    <a href="/ManagerSchool/Save" class="btn btn-primary btn-round ml-auto">
                        <i class="ti-plus"></i>
                        Lưu
                    </a>
                </div>
            </div>
        </div>
        <form id="formshool">
            <div class="card-body">

                <div class="table-responsive pt-3">
                    <table id="data-table" class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Mã Tỉnh
                                </th>
                                <th>
                                    Tên Tỉnh
                                </th>
                                <th>
                                    Mã Quận
                                </th>
                                <th>
                                    Tên Quận
                                </th>
                                <th>
                                    Mã Trường
                                </th>
                                <th>
                                    Tên Trường
                                </th>
                                <th>Địa Chỉ</th>
                                <th>
                                    Khu Vực
                                </th>

                            </tr>
                        </thead>
                        <tbody id="tbbody">
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td style="width:150px">
                                        <input disabled value="@item.idConscious" class="idConscious form-control" required />
                                    </td>
                                    <td style="width:400px">
                                        <input required value="@item.NameConscious" class="NameConscious form-control" />
                                    </td>
                                    <td style="width:150px">
                                        <input disabled value="@item.idDistrict" required class=" idDistrict form-control" />
                                    </td>
                                    <td style="width:400px">
                                        <input value="@item.NameDistrict" required class=" NameDistrict form-control" />
                                    </td>
                                    <td style="width:150px">
                                        <input disabled value="@item.idShool" required class=" idSchool  form-control" />
                                    </td>
                                    <td style="width:400px">
                                        <input value="@item.NameShool" required class=" NameSchool form-control" />
                                    </td>
                                    <td style="width:400px">
                                        <input value="@item.Adrees" required class="adress form-control" />
                                    </td>

                                    <td style="width:150px">
                                        <select required class=" Area form-control">
                                            <option value="KV1"> KV1</option>
                                            <option value="KV2"> KV2</option>
                                            <option value="KV3"> KV3</option>
                                            <option value="KV4"> 2NT</option>
                                        </select>
                                    </td>


                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="col-12 text-center">
                    <button type="submit" asp-controller="ManagerSchool" asp-action="Create" class="col-1 btn btn-primary">
                        Lưu
                    </button>
                </div>
            </div>

        </form>
    </div>
</div>

@section Scripts{

    <script>
    let arr = []
    var data = null;
    let cout = 10000;
    let majorsnew = [];
    let blocknew = [];
        $(document).ready(function () {
        $('#formshool').on('submit', function (e) {
            e.preventDefault(); // Now nothing will happen
            let check = true;
            arr = [];
            arr.push({
                idConscious: "",
                NameConscious: "",
                idDistrict: "",
                NameDistrict: "",
                NameShool: "",
                idShool: "",
                Adrees: "",
                Area: "",
            })
            for (var i = 0; i < $('.idConscious').length; i++) {
                arr.push({
                    idConscious: $($('.idConscious')[i]).val(),
                    NameConscious: $($('.NameConscious ')[i]).val(),
                    idDistrict: $($('.idDistrict')[i]).val(),
                    NameDistrict: $($('.NameDistrict')[i]).val(),
                    NameShool: $($('.NameSchool')[i]).val(),
                    idShool: $($('.idSchool ')[i]).val(),
                    Adrees: ($($('.adress')[i]).val() ? $($('.idConscious')[i]).val() : ""),
                    Area: $($('.Area')[i]).val(),
                })
                if (arr.length > 0) {
                    $.ajax({
                        url: "/ManagerSchool/Import",
                        type: 'POST',
                        data: { ViewSchool: JSON.stringify(arr) },
                        success: function (data) {
                            //...
                            window.location = "/ManagerSchool/ViewExcel"

                        }
                    });
                }

            }



        });




    })

    </script>

}