WebTuyenSinhAdmin/Controllers/AdmisstionController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;
using WebTuyenSinh.Data.Entityes;
using WebTuyenSinh_Application.Interface;
using WebTuyenSinh_Application.Modell;
using WebTuyenSinh_Application.Repository;
using WebTuyenSinh_Application.System;
using WebTuyenSinh_Application.ViewApi;
using WebTuyenSinhAdmin.Contan;

namespace WebTuyenSinhAdmin.Controllers
{
    public class AdmisstionController : Controller
    {
        private readonly IValidateTokenService _IValidateTokenService;
        private readonly IAdmisstionService _service;
        private readonly IManageMajorSevice manageMajor;
        private readonly IStorageService _storage;
        public AdmisstionController(IAdmisstionService service, IManageMajorSevice majorSevice , IStorageService storage, IValidateTokenService validateTokenService)
        {
            _service = service;
            manageMajor = majorSevice;
            _storage = storage;
            _IValidateTokenService = validateTokenService;
        }
        
        public async Task<IActionResult> GETProfile ( long? id)
            {
            ApiResult result = await _service.GetByProfile(id);
 
            return Ok(result);
        }
              public async Task<IActionResult> ProfileDetail(long? id)
        {
            try
            {
                string cookie = Request.Cookies[UserContant.UseToken];
                if (cookie == null || cookie.Length == 0)
                {
                    return RedirectToAction("Index", "Account");
                }
                var check = await _IValidateTokenService.ValidateToken(cookie, new List<long>() { PermisstionConTant.QL_TS, PermisstionConTant.QL_TH });
              
                if (id == null)
                {
                    return View("Error");
                }
                ApiResult result=await   _service.GetByProfile(id);
                ProfileView view = (ProfileView) result.Data;
          
                result = await _service.GetByID(view.Data.idAdmisstion);
                Admisstion Admisstion = (Admisstion)result.Data;
                ViewBag.data = Admisstion;
                if (!check)
                {
                    return View("UseNotFound");
                   
                }
                if (Admisstion.Type == 1)
                {
                    return View(view);
                   
                }
                else
                {
                    return View("Test", view);
                }
              
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }
        
        [HttpPost()]
        public async Task<IActionResult> Dowload(long? id , int Type)
        {

            ApiResult result = await _service.DowloadFile(id, Type);

            return Ok(result);
        }
        [HttpGet()]
        public async Task<IActionResult> GetAdmisstionInfo(long? id)
        {
        
            ApiResult result = await _service.GetAdmisstionInfo(id);
         
            return Ok(result);
        }
        [HttpPost()]
        public async Task<IActionResult> CreateProfile(ProfileStudent Profile,List<FileProfileView> files)
        {
            return Ok(await _service.CreateProfile(Profile, files));
        }
        public async Task<IActionResult> ListAll(long? id ,string ShoolName, int? page= 0)
        {
            try
            {
                string cookie = Request.Cookies[UserContant.UseToken];
                if (cookie == null || cookie.Length == 0)
                {
                    return RedirectToAction("Index", "Account");
                }
                if (id == null)
                {
                    return View("Error");
                }
                ApiResult result = await _service.ListAll(id);
                List<ProfileStudentsView> view = (List<ProfileStudentsView>)result.Data;
                ViewBag.Majo = result.Message;
              
                if (ShoolName != null && ShoolName.Length > 0) { view = view.Where(x => x.CMND.Contains(ShoolName) ||x.Teletephone.Contains(ShoolName) || x.Name.Contains(ShoolName) || x.id.ToString().Contains(ShoolName)  ).ToList(); }
                else
                {
                    ShoolName = "";
                }
                int limit = 10;
                int start;
                if (page > 0)
                {
                    page = page;
                }
                else
                {
                    page = 0;
                }
                start = (int)(page - 1) * limit;
                ViewBag.pageCurrent = page;
                ViewBag.Search = ShoolName;
                int totalProduct = view.Count;
                float numberpage = totalProduct / limit;
                ViewBag.numberPage = (int)Math.Ceiling(numberpage);        
                return View(view.Skip(start).Take(limit).ToList());
            }
            catch
            {
                return View("Error");
            }
        }
            public async Task<IActionResult> ListProfile(long? id)
        {
            try
            {
                string cookie = Request.Cookies[UserContant.UseToken];
                if (cookie == null || cookie.Length == 0)
                {
                    return RedirectToAction("Index", "Account");
                }
                if (id == null)
                {
                    return View("Error");
                }
                ApiResult result = await _service.ListProfile(id);
             List<ProfileStudentsView> view = (List<ProfileStudentsView>)result.Data;
                ViewBag.Majo = result.Message;
                return View(view);
            }
            catch
            {
                return View("Error");
            }
        }

        public async Task<IActionResult> Detail(long? id )
        {
            try {
                string cookie = Request.Cookies[UserContant.UseToken];
                if (cookie == null || cookie.Length == 0)
                {
                    return RedirectToAction("Index", "Account");
                }
                if (id == null)
                {
                    return View("Error");
                }
                ApiResult result = await _service.GetByID(id);
                Admisstion Admisstion = (Admisstion)result.Data;
                return View(Admisstion);
            }  catch { return View("Error");
    }
        }

        
          public async Task<IActionResult> ListAllFile()
        {
            string cookie = Request.Cookies[UserContant.UseToken];
            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
            var check = await _IValidateTokenService.ValidateToken(cookie, new List<long>() { PermisstionConTant.QL_TS, PermisstionConTant.QL_FILE });
            if (check)
            {
                var path1 = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Profile");
                // 2.Khai báo một thể hiện của lớp DirectoryInfo
                DirectoryInfo directory = new DirectoryInfo(path1);
                
                ViewBag.File = directory.GetFiles().Count();
                return View();
            }
            return View("UseNotFound");
        }

        public async Task<IActionResult> Block()
        {

            ApiResult result = await _service.GetBockAll();
            List<Block> Block = (List<Block>)result.Data;
            string cookie = Request.Cookies[UserContant.UseToken];
            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
            var check = await _IValidateTokenService.ValidateToken(cookie, new List<long>() { PermisstionConTant.QL_TS, PermisstionConTant.QL_TH});
            if (check)
            {
                return View(Block);
            }
            return View("BlockUse",Block);
        }
        public async Task<IActionResult> Index()
        {
            ApiResult result = await _service.GetAll(4);
            List<Admisstion> Admisstion = (List<Admisstion>)result.Data;
            string cookie = Request.Cookies[UserContant.UseToken];
            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
            var check = await _IValidateTokenService.ValidateToken(cookie, new List<long>() { PermisstionConTant.QL_TS });
            if (check)
            {
                return View(Admisstion);
            }
            return View("IndexUse",Admisstion);

        }
        [HttpGet]
        public async Task<IActionResult> Result()
        {
            string cookie = Request.Cookies[UserContant.UseToken];
            if (cookie == null || cookie.Length == 0)
            {
                return RedirectToAction("Index", "Account");
            }
            ApiResult result = await _service.GetAll(4);
            List<Admisstion> Admisstion = (List<Admisstion>)result.Data;
           
          
            return View(Admisstion);
        }
        
         [HttpGet]
        public async Task<IActionResult> Export(long? id)
        {

            ApiResult result = await _storage.ExportExcell(id);

            return Ok(result);

        }
        [HttpGet]
        public async Task<IActionResult> ExportExcellOne(long? id)
        {

            ApiResult result = await _storage.ExportExcellOne(id);

            return Ok(result);

        }

        [HttpGet]
        public async Task<IActionResult> GetResult(long? id)
        {

               
                ApiResult result = await _service.GetProfiles(id);

                return Ok(result);
            

WebTuyenSinhAdmin/Views/Admisstion/Detail.cshtml
@model Admisstion
@{



}
@using WebTuyenSinh_Application.Repository;
@using WebTuyenSinh.Data.Entityes;

<div class="col-lg-12 grid-margin stretch-card" id="frm1">
    <div class="card">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="m-3 border-bottom pb-3">
                        <div class="d-flex align-items-center">
                            <h4 class="card-title">Thông Tin Xét Tuyển</h4>
                            <div class="ml-auto">
                                <a href="/Admisstion/ListAll/@Model.id" class="btn btn-primary btn-sm ">Xem danh sách thí sinh</a>
                                <a href="/Admisstion/Index" class="btn btn-primary btn-sm ">Quay Về</a>
                            </div>
                        </div>

                    </div>
                
                        <div class="card-body">
                            <form id="formadmisstion">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="mb-3 row ">
                                            <div class="col">
                                                <input type="text" class="form-control" id="txtid" hidden value="@Model.id" required placeholder="Mời Nhập Thông Tin">
                                                <label for="txtname" class="form-label mr-2 fw-bold">Nội Dung :</label>
                                                <label for="txtname" class="form-label">@Model.Name </label>


                                            </div>
                                            <div class="col">
                                                <label for="txttype" class="form-label mr-2 fw-bold">Hình Thức Xét Tuyển</label>
                                                <label for="txtname" class="form-label">@(Model.Type==1 ? "Xét Đánh Giá Năng Lực":"Xét Học Bạ") </label>


                                            </div>

                                        </div>

                                    </div>
                                    <div class="col d-flex justify-content-between align-items-center">
                                        <label class="mr-2 fw-bold">Thời Gian Bắt Đầu</label>
                                        <label class="w-50">@Model.OpenTime.Value.ToString("dd/MM/yyyy  HH:mm tt") </label>

                                    </div>
                                    <div class="col d-flex justify-content-between align-items-center">
                                        <label class="mr-2 fw-bold">Thời Gian Kết Thúc</label>
                                        <label class="w-50">@Model.CloseTime.Value.ToString("dd/MM/yyyy  HH:mm tt") </label>

                                    </div>

                                </div>
                                
                                <div class="row">
                                    <div class="col-12">
                                        <div class="table-responsive">
                                            <table id="data-table" class="expandable-table text-center" style="width:100%">
                                                <thead>
                                                    <tr class="">
                                                        <th>
                                                            Mã Ngành
                                                        </th>
                                                        <th>
                                                            Tên Ngành
                                                        </th>
                                                        <th>
                                                            Tổ Hợp Môn
                                                        </th>
                                                        <th>
                                                            Số Lượng Dự Kiến
                                                        </th>
                                                        <th>
                                                            Số Thí Sinh Tham Dự
                                                        </th>
                                                        <th>
                                                            #
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody id="tbbody">
                                                    @{
                                                        var i = 0;
                                                        @foreach (var item in Model.Admisstion_Major)
                                                        {
                                                            i++;
                                                            <tr>
                                                                <td>
                                                                    @item.Major.id
                                                                </td>
                                                                <td>
                                                                    @item.Major.Name
                                                                </td>
                                                                <td>
                                                                    @foreach (var item1 in item.Addmisstion_Major_Block)
                                                                    {
                                                                        @(item1.idBlock.ToString()+" ,");
                                                                    }
                                                                </td>
                                                                <td>
                                                                    @item.Quantity

                                                                </td>
                                                                <td>
                                                                    @item.Count

                                                                </td>
                                                                <td>
                                                                    <a href="/Admisstion/ListProfile/@item.id" data-toggle="tooltip" title="" class="btn  btn-icon-text text-primary  " data-original-title="Edit Task">
                                                                        <i class=" ti-eye"></i>
                                                                    </a>
                                                                </td>
                                                            </tr>

                                                        }

                                                    }

                                                </tbody>
                                            </table>

                                        </div>

                                    </div>

                                </div>
                            </form>
                        </div>
                    
               


                </div>
            </div>
        </div>

    </div>
</div>

WebTuyenSinhAdmin/Views/Admisstion/ListAllFile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card" style="height:100px">
                <h4>Hệ thống đang có @ViewBag.File</h4>
            </div>
        </div>
    </div>
</div>
              

WebTuyenSinhAdmin/Views/Admisstion/ListAllProfile.cshtml
@model List<ProfileStudentsView>
@{

}
@using WebTuyenSinh_Application.ViewApi;

<style>
    .show {
        z-index: 1000;
        position: absolute;
        display: block;
        margin: 0;
        list-style-type: none;
        list-style: none;
    }

    .hide {
        display: none;
    }

    .show li {
        list-style: none;
    }

    .show a {
        border: 0 !important;
        text-decoration: none;
    }

        .show a:hover {
            text-decoration: underline !important;
        }
</style>

<div class="hide" id="rmenu">
    <div class="list-group">
    </div>

</div>
<div class="col-lg-12 grid-margin stretch-card" id="frm1">
    <div class="card">
        <div class="m-3 border-bottom pb-3">
            <div class="d-flex align-items-center">
                <h4 class="card-title mr-4 ">Danh Sách Hồ Sơ @ViewBag.Majo</h4>
                @using (Html.BeginForm("ListAllProfile", "Admisstion", FormMethod.Get))
                {
                    <div class=" ml-auto services-search col-11 ">

                        <div class="search-input">
                            <input type="text" name="Search" class="form-control search-input-area" value="@((string)ViewBag.search)" id="" placeholder="Tìm kiếm hồ sơ">

                            @Html.Hidden("page", (object)ViewBag.pageCurrent)
                            @Html.Hidden("ID", (object)ViewBag.ID)

                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body text-center">
                  
                        <div class="row">
                           
                            @foreach (var item in Model)
                            {
                                <div class="col-2 text-center">
                                    <a class="" href="/Admisstion/ProfileDetail/@item.id">
                                        <img class="rounded mx-auto d-block test" id="@item.id" width="100" src="~/images/pngtree-vector-folder-icon-png-image_555545.jpg" />

                                        @(item.CMND+"_"+item.Name)
                                    </a>
                                </div>
                            }
                            <br />
                            <div class="d-flex align-items-center">
                                <div class="ml-auto">
                                    <ul class="pagination">
                                        @{
                                            int numberPage = ViewBag.numberPage;
                                            int pageCurrent = ViewBag.pageCurrent;
                                            int offset = 2;//number display page


                                            //config FirstLink
                                            if (pageCurrent > 1)
                                            {
                                                int prevPage = pageCurrent - 1;
                                                var PrevLink = new Dictionary<string, string> { { "page", prevPage.ToString() } };
                                                <li><a asp-controller="Admisstion" asp-action="ListAllProfile" asp-all-route-data="PrevLink">Prev Link</a></li>
                                            }

                                            int from = pageCurrent - offset;
                                            int to = pageCurrent + offset;
                                            if (from <= 0)
                                            {
                                                from = 1;
                                                to = offset * 2;
                                            }


                                            if (to > numberPage)
                                            {
                                                to = numberPage;
                                            }

                                            int i;
                                            for (i = from; i <= to; i++)
                                            {
                                                var parms = new Dictionary<string, string>
                                                                                                                                                                                                                                        {
                        { "page",i.ToString()},{"ID",ViewBag.ID},{"Search",ViewBag.search}
                            };
                                                if (pageCurrent == i)
                                                {
                                                    <li class="active"><a asp-controller="Admisstion" asp-action="ListAllProfile" asp-all-route-data="parms">@i</a></li>
                                                }
                                                else
                                                {
                                                    <li><a asp-controller="Admisstion" asp-action="ListAllProfile" asp-all-route-data="parms">@i</a></li>
                                                }

                                            }

                                            if (pageCurrent < numberPage - (to / 2))
                                            {
                                                <li><a>...</a></li>
                                                var LastLink = new Dictionary<string, string> { { "page", numberPage.ToString() } };
                                                <li><a asp-controller="Admisstion" asp-action="ListAllProfile" asp-all-route-data="LastLink">Last Link</a></li>
                                            }

                                            if (pageCurrent < numberPage)
                                            {
                                                int nextPage = pageCurrent + 1;
                                                var NextLink = new Dictionary<string, string> { { "page", nextPage.ToString() } };
                                                <li><a asp-controller="Admisstion" asp-action="ListAllProfile" asp-all-route-data="NextLink">Next Link</a></li>
                                            }
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        @if (Model.Count == 0)
                        {
                            <h4>Chưa có hồ sơ gửi về</h4>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="position-fixed end-0 mt-5 pt-2 " style="z-index: 11">
            <div id="liveToast" class="toast hide bg-success text-white p-2" role="alert" aria-live="assertive" aria-atomic="true">

            </div>
        </div>
        <div class="position-fixed end-0 mt-5 pt-2 " style="z-index: 11">
            <div id="livefail" class="toast hide bg-danger text-white p-2" role="alert" aria-live="assertive" aria-atomic="true">
                Cập nhật thất bại
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        if ($("#test").addEventListener) {
            $("#test").addEventListener('contextmenu', function (e) {
                e.preventDefault();
            }, false);
        } else {

            //document.getElementById("test").attachEvent('oncontextmenu', function() {
            //$(".test").bind('contextmenu', function() {
            $('body').on('contextmenu', 'img.test', function (e) {
                //alert("contextmenu"+event);
                document.getElementById("rmenu").className = "show";
                document.getElementById("rmenu").style.top = mouseY(event) + 'px';
                document.getElementById("rmenu").style.left = mouseX(event) + 'px';
                $("#rmenu").empty();
                $("#rmenu").append(`<div class="list-group">
                    <a href="/Admisstion/ProfileDetail/${e.target.id}" class="list-group-item list-group-item-action">  <i class="ti-eye"></i></a>
                    <button name="Dowload" id="${e.target.id}" class="list-group-item list-group-item-action"><i class="ti-download"></i></button>
                </div>`);
                window.event.returnValue = false;
            });
        }

    });

    // this is from another SO post...
    $(document).bind("click", function (event) {
        document.getElementById("rmenu").className = "hide";
    });

    function mouseX(evt) {
        if (evt.pageX) {
            return evt.pageX;
        } else if (evt.clientX) {
            return evt.clientX + (document.documentElement.scrollLeft ?
                document.documentElement.scrollLeft :
                document.body.scrollLeft);
        } else {
            return null;
        }
    }

    function mouseY(evt) {
        if (evt.pageY) {
            return evt.pageY;
        } else if (evt.clientY) {
            return evt.clientY + (document.documentElement.scrollTop ?
                document.documentElement.scrollTop :
                document.body.scrollTop);
        } else {
            return null;
        }
    }
</script>


@section Scripts{
    <script>
        $(document).ready(function () {
            $(document).on('click', "button[name = 'Dowload']", function () {
                let id = $(this).attr("id")
                $.ajax({
                    async: false,
                    url: "/Admisstion/Dowload/" + id,
                    type: 'POST',
                    data: { id: id, type: 2 }
                }).done(function (res) {
                    if (res.success) {
                        var link = document.createElement('a');
                        link.href = res.data;
                        link.download = `${res.message}`;
                        link.click();
                        link.remove();
                    }

                })

            });
        })
    </script>
}